### ISSUE TITLE
google plus doesn work

### ISSUE THREAD

**Issue by jpca999** [cornflourblue/angulike#13]
google plus doesn't work

![image](https://cloud.githubusercontent.com/assets/1026325/7078588/30e5d99e-decf-11e4-83d1-da8a1b45e367.png)

**Comment by cornflourblue** [comment]
It's working for me - http://jasonwatmore.com/post/2014/08/01/AngularJS-directives-for-social-sharing-buttons-Facebook-Like-GooglePlus-Twitter-and-Pinterest.aspx

Can you create a plunk showing the issue?

**Comment by jpca999** [comment]
it doesnt work other there too..  here's the screenshot .. 

https://www.dropbox.com/s/ubmzmz3fdg6780s/Screenshot%202015-04-09%2016.51.59.png?dl=0
![screenshot 2015-04-09 16 51 59](https://cloud.githubusercontent.com/assets/1026325/7079408/da0250d0-ded8-11e4-85cf-41123871a3f8.png)

**Comment by jpca999** [comment]
see the google icon became weird.  Try it out yourself.

**Comment by cornflourblue** [comment]
This is how I'm seeing it, my guess would be it's something related to your machine or local network, maybe a proxy or firewall blocking a request from the google+ script?

![angulike](https://cloud.githubusercontent.com/assets/785317/7079513/6d6ac340-df68-11e4-9670-3dac1e92021f.png)

**Comment by cornflourblue** [comment]
Not an issue with the directive
