### ISSUE TITLE
how do i make the image to be displayed when I click like and write comment on it. On my facebook wall it doesnt display the image. 

### ISSUE THREAD

**Issue by jpca999** [cornflourblue/angulike#16]

**Comment by jpca999** [comment]
https://www.dropbox.com/s/v8ik75duyvx91oh/Screenshot%202015-04-09%2018.12.43.png?dl=0

**Comment by cornflourblue** [comment]
This is controlled with open graph meta tags within your page, the like/share button just sends a URL to facebook, facebook crawls the URL to get the info about the page.

Check out http://davidwalsh.name/facebook-meta-tags for more info.
