### ISSUE TITLE
Is this working with android and ios hybrid app? 

### ISSUE THREAD

**Issue by Bmkaradia** [cornflourblue/angulike#24]
Hi

Thanks for better directive ,   I created a apk for android and install on device, but below message shows. 

my question is : does this work for app?

if (window.location.href.indexOf('http') != 0) {
    alert("This demo must be run on a web server (i.e. the url must start with http/https), it won't work by opening the file directly in a browser.");
}

Thanks
Brijmohan

**Comment by ranvirgorai** [comment]
In my case when i use angular app then its works fine, But when i adding same plugin to ionic project it is not working, Error msg = **violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'"**

**Comment by ranvirgorai** [comment]
Yes it is working, But Not As Expected !...

**Comment by Bmkaradia** [comment]
thanks Ranvirgoraj
