### ISSUE TITLE
Demo does not show the facebook button

### ISSUE THREAD

**Issue by leolux** [cornflourblue/angulike#32]
The demo at http://jasonwatmore.com/post/2014/08/01/angularjs-directives-for-social-sharing-buttons-facebook-like-google-plus-twitter-and-pinterest does not work for facebook

Same for http://embed.plnkr.co/TQoIJ2/?show=preview

**Comment by cornflourblue** [comment]
It's working on the blog post now and at http://plnkr.co/edit/TQoIJ2?show=preview&p=preview

The embedded view has issues because plunker uses a sandboxed iframe.
