### ISSUE TITLE
bower install with latest angular fails due to version mismatch.

### ISSUE THREAD

**Issue by adriannye** [cornflourblue/angulike#9]
Unable to find a suitable version for angular, please choose one:
    1) angular#~1.2.16 which resolved to 1.2.28 and is required by angulike#de2ec79068
    2) angular#~1.3.10 which resolved to 1.3.10 and is required by songrhyme
    3) angular#1.3.10 which resolved to 1.3.10 and is required by angular-route#1.3.10
    4) angular#~1 which resolved to 1.3.11 and is required by ngDialog#0.3.9

**Comment by cornflourblue** [comment]
This should work for you now

**Comment by adriannye** [comment]
Thank you!
